services:
  gateway:
    build: 
      context: ./services/gateway
    ports:
      - "8000:8000"
    # LOGIC: Move the connection string here so it's impossible to mismatch
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/careerflow_db
      - DRY_RUN=True
    volumes:
      - ./services/gateway:/app
    depends_on:
      db:
        condition: service_healthy # Wait for the DB to be FULLY ready
    networks:
      - careerflow-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: careerflow_db
    healthcheck: # LOGIC: Tells other services when the DB is actually 'alive'
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - careerflow-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ai-engine:
    build: ./services/ai-engine
    ports:
      - "8001:8000"
    env_file:
      - .env  
    volumes:
      - ./services/ai-engine:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - careerflow-network

  frontend:
    build: ./services/frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - gateway

  gmail-agent:
    build:
      context: ./services/agents         
      # dockerfile: Dockerfile
    # depends_on:
    #   db:
    #     condition: service_healthy
    #   ai-engine:
    #     condition: any
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/careerflow_db
      - AI_ENGINE_URL=http://ai-engine:8000/process
    volumes:
      - ./services/agents/token.json:/app/token.json
    networks:
      - careerflow-network

volumes:
  postgres_data:

networks:
  careerflow-network:
    driver: bridge